### PR TITLE
replace 64bit integer type with string

### PR DESCRIPTION
**Pull request by muddle216**
With --ts_opt=int64_to_string=true, protoc will generate string field for int64, uint64, etc. if everything runs ok. But I don't know how to test it with protoc. Is there anyone who can help me?

### CODE REVIEW

**Comment by chris-kruining** [comment]
over at #117 @thesayyn has given a small explanation on how to write tests, you could take a peek at that ;)

**Comment by thesayyn** [comment]
Why not just use JS_STRING?  Perhaps something missing here but isn't the whole point of JS_STRING to get bigints (64) as string?

**Comment by muddle216** [comment]
In my case, proto files are stored in a common repository which is shared by many projects that coded by different languages. The other reason is there are a lot of exist proto files, which have not been modified for a long time. So I prefer to add an option as a global flag, that do not need to modify proto files.

I am testing my version ts files in my project. And I will push another commit when I have enough test done.

**Comment by muddle216** [comment]
In my case, proto files are stored in a common repository which is shared by many projects that coded by different languages. The other reason is there are a lot of exist proto files, which have not been modified for a long time. So I prefer to add an option as a global flag, that do not need to modify proto files.

I am testing my version ts files in my project. And I will push another commit when I have enough test done.

**Comment by thesayyn** [comment]
I somehow have mixed feelings about introducing a new option every time we need to override the behavior of protoc. I understand in your use case, it is charming to have an option that does it all but it is a maintenance burden to us.  

I would understand if you were going to replace `[u-s|fixed]int64` with `BigInt` since that's the whole point of `protoc-gen-ts`, make js ecosystem play well with protoc.

**Comment by thesayyn** [comment]
Feel free to open another PR if still believe protoc-gen-ts should have this option.

**Pull request closed without merging**
