### PR TITLE
TypeScript working, need to figure out build

### PR DESCRIPTION
**Pull request by koblas**
This is a conversion of the JavaScript code to TypeScript, it cleans up a ton of small issues.  It also adds eslint to the system as part of the change to help catch more errors.

Currently Open -

I cannot figure out how to get bazel working with typescript and this testing.  I'll fully admit I have no idea how `bazel` work, but thought I could figure it out, but failed..  

Help?!

### CODE REVIEW

**Comment by thesayyn** [comment]
1. that's definitely true and has to be properly enforced.
2. I partially agree with the part "ts code and ts ast" but I will not enforce my opinions over community opinions.

i will help you get the tests pass asap.

**Comment by thesayyn** [comment]
Hey, @koblas.  I was busy getting back to Germany and now I just got the windows issue fixed and I can focus on this one.

**Comment by thesayyn** [comment]
Hey @koblas, do you have the bandwidth to pick this up again?

**Comment by koblas** [comment]
I do!  I'll dig into this tomorrow

**Comment by thesayyn** [comment]
> I do! I'll dig into this tomorrow

Thank you. I have a strong feeling that this gonna help people contribute easily and with confidence.

**Comment by koblas** [comment]
@thesayyn this appears to be passing tests locally for me.

**Comment by thesayyn** [comment]
@koblas will you be able rebase?

**Comment by koblas** [comment]
Ok, rebased.  Feel free to figure out how I broke the build.  The initial errors look like it's a submodule thing, but I'm sure there is some bazel error in there.

I did have it running the tests to completion on my machine before the rebase

**Comment by thesayyn** [comment]
thanks a lot. i will take over from here. will try to land this week.

**Comment by chris-kruining** [comment]
@thesayyn Do you reckon the test fails because it is trying to copy a file from a submodule that is not checked out during setup?

**Comment by thesayyn** [comment]
did you pull the submodules?  `git submodule update --init --recursive`

**Comment by chris-kruining** [comment]
no, I meant the failing tests on this PR

**Comment by thesayyn** [comment]
it ought to work. but seems like @koblas changed the copy script in a way that wouldn’t work. seems like you have to clean up this a little bit. just hard reset those files you see as unnecessary change.

**Comment by chris-kruining** [comment]
is it ok to switch build systems? I reckon I can get a nice setup with esbuild and a docker image for generating the js code.

**Comment by thesayyn** [comment]
> is it ok to switch build systems? I reckon I can get a nice setup with esbuild and a docker image for generating the js code. wouldn't that be literally the same?  I would like to keep bazel as the build system nevertheless.

**Comment by koblas** [comment]
My $0.02 -- bazel works and is very "google" of the system, but if you're not used to working with the nuances of bazel (which I admit I'm a rank amateur) it's pretty complicated.   It's unclear to me what the benefit it brings to the system is.

**Comment by thesayyn** [comment]
> My $0.02 -- bazel works and is very "google" of the system, but if you're not used to working with the nuances of bazel (which I admit I'm a rank amateur) it's pretty complicated. It's unclear to me what the benefit it brings to the system is.

I agree on how it can be so complicated for a beginner.  if you @koblas and @chris-kruining believe `protoc-gen-ts` should not depend on it, I am totally okay with that. I don’t own protoc-gen-ts.

If we can match the current testing coverage with something else I am totally on board. i don’t wanna give up on speed and e2e tests that we have.

**Comment by thesayyn** [comment]
Closing this one in favor of #111. Thank you @koblas for pushing this.

**Pull request closed without merging**
