### PR TITLE
add override keyword to deserializeBinary

### PR DESCRIPTION
**Pull request by td-krzysiek**
#138 looked quite easy so I added it too.

### CODE REVIEW

**Comment by td-krzysiek** [comment]
ah, not that easy then since there is v14 support...

**Comment by thesayyn** [comment]
> ah, not that easy then since there is v14 support...

The node version shouldn't matter IMHO. it's just there to assert that we don't use something that's only available at 16.x. Probably `override` keyword was introduced in the newer version of typescript. so you could hide that behind a feature gate. maybe something like `--ts_opt=explicit_override=true` ?

**Comment by td-krzysiek** [comment]
true, good point, this will now require some on/off tests.

**Comment by thesayyn** [comment]
> true, good point, this will now require some on/off tests.

https://github.com/thesayyn/protoc-gen-ts/blob/main/test/_/no_namespace/BUILD.bazel#L18  is a good example of this. leave original tests as is and create a new directory containing a proto with the feature gate flipped on like in the example.

**Comment by td-krzysiek** [comment]
windows thing again 😅, anyway I think it should be good for the review now.

**Review by thesayyn — APPROVED** [review]

**Pull request merged**
