### PR TITLE
[add] suport [jstype = JS_STRING]

### PR DESCRIPTION
**Pull request by chenxyzl**

### CODE REVIEW

**Comment by thesayyn** [comment]
I am sorry about the delay. I have been busy with my work and school. So this weekend I'll provide some testing utilities and update your PR with some test cases and then finally we can merge this PR.

Maybe we can catch up this weekend? If you are available?

**Comment by chenxyzl** [comment]
Sorry, I wanted to submit only a few commit. Now this PR seems to be corrupted by my other meaningless submissions.

**Comment by thesayyn** [comment]
@chenxyzl I have made some changes on the upstream to improve readability of the code. I'm gonna need you to rebase it.

**Comment by chenxyzl** [comment]
I'm sorry I've been busy recently. I'll be back when the project comes online.

**Pull request closed without merging**
