### PR TITLE
annotate one_of_decls

### PR DESCRIPTION
**Pull request by td-krzysiek**
Hi,

I have a TypeScript errors due to missing type annotation of `#one_of_decls`. This pull request solves the problem.

### CODE REVIEW

**Comment by thesayyn** [comment]
It looks okay to me; can you add a test that asserts this never going to go unnoticed? perhaps it's a tsconfig option?

**Comment by td-krzysiek** [comment]
This will be noImplicitAny but to enable it I had to make a few other changes.

**Comment by td-krzysiek** [comment]
Hm... I don't know what this windows error means, any idea?

**Comment by thesayyn** [comment]
> Hm... I don't know what this windows error means, any idea?

Probably a flaky test.

**Review by thesayyn — APPROVED** [review]
looks good thanks!

**Comment by td-krzysiek** [comment]
Thanks!

**Pull request merged**
