### PR TITLE
Add default when mapping from repeating responses

### LINKED ISSUE #188: fromObject does not check for nullables when mapping
I have a proto file that depends on `google/api/protobuf/descriptor` (I'm using definitions from `google-proto-files=3.0.2` package) and building it like so:
`protoc -I=./node_modules/google-proto-files/ -I=. --ts_opt=unary_rpc_promise=true --ts_opt=no_namespace --ts_out=./src/generated rpc.proto`

It does work and generates various ts files, but all `fromObject` methods that interact with arrays (those in the `descriptor` proto file) have an error that prevent me from "compiling" ts.

```log
src/generated/google/protobuf/descriptor.ts:28:19 - error TS2532: Object is possibly 'undefined'.

28             file: data.file.map(item => FileDescriptorProto.fromObject(item))
                     ~~~~~~~~~

src/generated/google/protobuf/descriptor.ts:233:27 - error TS2532: Object is possibly 'undefined'.

233             message_type: data.message_type.map(item => DescriptorProto.fromObject(item)),
                              ~~~~~~~~~~~~~~~~~
...
```

Adding conditional access `?.` and a default `?? []`  would already make it work

I'm just getting started with protoc so any recommendations are welcome :)

### PR DESCRIPTION
**Pull request by johnnyasantoss**
Fixes #188

### CODE REVIEW

**Comment by thesayyn** [comment]
i think you need to run tests first to check in the generated files.

**Comment by johnnyasantoss** [comment]
@thesayyn Is there a script to regenerate the test clients that are failing the tests? I have no past experience with bazel and it would be really helpful for collaboration if the workspace had scripts to do all these chores.

not sure if they were generated manually

**Comment by johnnyasantoss** [comment]
@thesayyn are you planning on releasing a new version of this package with this fix? It would be better than pointing to the commit hash with a package manager

**Comment by thesayyn** [comment]
@johnnyasantoss it might take me some time to cherry pick your change to rust.

**Pull request merged**
