### PR TITLE
added optional ChannelOptions to client constructor

### PR DESCRIPTION
**Pull request by davearata-snorack**
in `@grpc/grpc-js` the interface `ServiceClientConstructor` has these parameters `(address: string, credentials: ChannelCredentials, options?: Partial<ChannelOptions>)`. Added the third options parameter to the generated client constructor.

### CODE REVIEW

**Review by thesayyn — COMMENTED** [review]
LGTM but a small addition.  Can we add a test for this changes?

**Comment by davearata-snorack** [comment]
Thanks for the feedback. Any suggestions on the test? I did some research doesn't seem like there is any good way to spy on a constructor.

**Comment by thesayyn** [comment]
> Thanks for the feedback. Any suggestions on the test? I did some research doesn't seem like there is any good way to spy on a constructor.

1- you could change the behavior of the rpcs by passing them different options and assert if those options take effect. Just an idea.
2- you could check if the given parameter reach out the underlying class. (you might have to access to a  private variable in the underlying class).
 
I'd prefer the first way since it is foolproof.

**Comment by davearata-snorack** [comment]
> > Thanks for the feedback. Any suggestions on the test? I did some research doesn't seem like there is any good way to spy on a constructor.
> 
> 1- you could change the behavior of the rpcs by passing them different options and assert if those options take effect. Just an idea.
> 2- you could check if the given parameter reach out the underlying class. (you might have to access to a private variable in the underlying class).
> 
> I'd prefer the first way since it is foolproof.

@thesayyn I implemented a test that checks that the options get applied to the channel object that is created.

**Pull request merged**
