### PR TITLE
Typescript chanches

### PR DESCRIPTION
**Pull request by chris-kruining**
as per https://github.com/thesayyn/protoc-gen-ts/pull/111#issuecomment-1018346251

### CODE REVIEW

**Comment by thesayyn** [comment]
can you squash them so that they are easy to cherry-pick?

**Comment by chris-kruining** [comment]
Pretty sure this should do the trick?

**Comment by thesayyn** [comment]
Yea. thanks a lot. just fixed a lot bazel related stuff. still trying to get windows pass. pain.

**Comment by chris-kruining** [comment]
> Yea. thanks a lot. just fixed a lot bazel related stuff. still trying to get windows pass. pain.

looking at the error it almost seems like it is looking for the submodule?

**Comment by thesayyn** [comment]
> looking at the error it almost seems like it is looking for the submodule?

just permission errors.

**Comment by thesayyn** [comment]
@chris-kruining the branch is ready. could you rebase and resolve conflicts? one last time I promise.

**Comment by chris-kruining** [comment]
> @chris-kruining the branch is ready. could you rebase and resolve conflicts? one last time I promise.
> 
> i don't need anything that is outside `src/` so you can leave them out.

My client wouldn't allow me to rebase on /src alone, so you might wanna cherry pick again, So I hope I did this right

**Comment by thesayyn** [comment]
it's worse now tbh. there are conflicts remaining in the files.

**Comment by chris-kruining** [comment]
dammit, I'll just reset the branch and manually re-add the files

**Comment by chris-kruining** [comment]
wait?! why did it close? because I reset all the changes?

**Comment by thesayyn** [comment]
probably. no worries. just send another one against typescript branch.

**Comment by chris-kruining** [comment]
ok, should be fine now.

**Comment by thesayyn** [comment]
Perfect!

**Comment by chris-kruining** [comment]
what an adventure with git today 🤣

**Pull request merged**
