### PR TITLE
Add Compiler Options for camelCase methodNames and creating namespaces

### PR DESCRIPTION
**Pull request by davearata-snorack**
With these compiler options namespaces are optional as well as method names for services have the option to be camelCase

### CODE REVIEW

**Comment by thesayyn** [comment]
Hey. I just got back from a long trip.  I will need a few days to review this.

**Comment by thesayyn** [comment]
Hey, again @davearata-snorack. Could you rebase?

**Comment by davearata-snorack** [comment]
> Hey, again @davearata-snorack. Could you please rebase?

Just pushed the rebase. Let me know if you have any other feedback. Thanks :)

**Comment by thesayyn** [comment]
Hey @davearata-snorack 

I am kind of busy with other stuff atm. I will get to this as soon as possible.

**Comment by thesayyn** [comment]
As far as I can tell it looks good so far but it needs a bit of work to get better. missing points goes as 

- Add documentation for the new behavior and explain the `--ts_opt` that corresponds to these options.
- Add tests for the new behavior

**Comment by thesayyn** [comment]
I'd be willing to merge this PR if anyone is up for writing tests for it.

**Pull request closed without merging**
