### PR TITLE
Default values

### LINKED ISSUE #107: Default values are not set.
Alot of implementations omit default values when serializing protobufs. So e.g. enums set to 0 will not be sent over the wire. When the message is deserialized this missing value should be set to the default value of 0. However default values will not be set by protoc-gen-ts. This causes problems with interoperability between e.g. C# and JavaScript/TypeScript as in our case. I investigated the generated code a bit and my suspect is this

**src/compiler/descriptor.js**
```js
// ...
 constructor(data?: any[] | {
            my_enum?:  Payload.SomeEnum
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], []);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("my_enum" in data && data.my_enum != undefined) {
                    this.my_enum = data.my_enum;
                }
            }
        }

// ...
```

If I read this correct then the value is only set if it is there but according to the specification it should be set to the default value 0.

### PR DESCRIPTION
**Pull request by Yurzel**
fixes #107 

**Changes**
- getters changed to getFieldWithDefault
- toObject returns undefined in proto2 and default value in proto3
- serialization was using getters so had to change to getField conditions
- serialization check array length
- added tests

Presence fields and proto3 to not serialize default values yet to come...

### CODE REVIEW

**Comment by thesayyn** [comment]
Has some failing tests. probably you need to run `yarn update update_checked_in`

**Comment by thesayyn** [comment]
> * serialization was using getters so had to change to getField conditions

Why is that the case? could you elaborate a bit on this?

**Comment by Yurzel** [comment]
> > * serialization was using getters so had to change to getField conditions
> 
> Why is that the case? could you elaborate a bit on this?

Because getters return default values now. Meaning the condition would always result true. That means the value would be serialized even when the field is null.

**Comment by thesayyn** [comment]
> > > * serialization was using getters so had to change to getField conditions
> > 
> > 
> > Why is that the case? could you elaborate a bit on this?
> 
> Because getters return default values now. Meaning the condition would always result true. That means the value would be serialized even when the field is null.

That sounds like the suboptimal solution to me. How about we use the presence fields to check if the value is set?

**Comment by thesayyn** [comment]
Perhaps we could pull off another trick to not serialize value if the value is the default? I don't like getField calls flying everywhere.

**Comment by td-krzysiek** [comment]
Hello,

this is something we are looking after too. Currently the generated code isn't as per the proto3 specification:

```Also note that if a scalar message field is set to its default, the value will not be serialized on the wire.```

[proto3](https://developers.google.com/protocol-buffers/docs/proto3#default)

**Comment by thesayyn** [comment]
> Hello,
> 
> this is something we are looking after too. Currently the generated code isn't as per the proto3 specification:
> 
> `Also note that if a scalar message field is set to its default, the value will not be serialized on the wire.`
> 
> [proto3](https://developers.google.com/protocol-buffers/docs/proto3#default)

Do you mind picking this up and making it green? so we can review and iterate?

**Comment by td-krzysiek** [comment]
Possibly, your library may solve quite a few difficulties we have with types from `ts-protoc-gen`. This will be slightly larger task so I'll discuss with team on Monday.

**Comment by Yurzel** [comment]
I wish I could help you but I have no idea where the problem is. We managed to use my branch to generate our desired typescript model.

If you get it to work please let me know what was the issue. I'm really curious.

**Comment by thesayyn** [comment]
Superseded by #146

**Pull request closed without merging**
