### PR TITLE
feat: make input arrays readonly

### LINKED ISSUE #211: Array parameters should be readonly
The code that's generated does not use `readonly` in places where it should:
```ts
export declare class BatchGetAccountsRequest extends pb_1.Message {
    #private;
    constructor(data?: any[] | {
        ids?: string[];
    });
    get ids(): string[];
    set ids(value: string[]);
    static fromObject(data: {
        ids?: string[];
    }): BatchGetAccountsRequest;
    toObject(): {
        ids?: string[];
    };
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): BatchGetAccountsRequest;
    serializeBinary(): Uint8Array;
    static deserializeBinary(bytes: Uint8Array): BatchGetAccountsRequest;
}
```
All parameters should declare their arrays as `readonly` to work with the following example code:
```ts
  getByIds(ids: readonly string[]): Promise<Account[]> {
    return this.client
      .BatchGetAccounts(new BatchGetAccountsRequest({ ids }))
      .then((res) => res.accounts.map(accountGrpcToJs));
  }
```

`The type 'readonly string[]' is 'readonly' and cannot be assigned to the mutable type 'string[]'.`

### PR DESCRIPTION
**Pull request by jeengbe**
I can't re-open the old MR because I had deleted the repository between then and now

See #236

Fixes #211

### CODE REVIEW

**Comment by thesayyn** [comment]
legacy-js is discontinued. can you make this change against rust version?

**Comment by jeengbe** [comment]
Is the Rust version published already?

**Comment by thesayyn** [comment]
the alpha version is published already; https://github.com/thesayyn/protoc-gen-ts/pkgs/npm/protoc-gen-ts

**Comment by jeengbe** [comment]
No can do, I fear. I haven't worked enough with Rust to get that done in a reasonable amount of time.

**Comment by jeengbe** [comment]
However please consider #211 in your further progress on the new package. It's a tiny detail 🙂

**Pull request closed without merging**
