### PR TITLE
Add no_namespace option

### PR DESCRIPTION
**Pull request by chris-kruining**

### CODE REVIEW

**Comment by chris-kruining** [comment]
depends on #111

**Comment by thesayyn** [comment]
iterator methods seem really cool. the only thing that I see is not acceptable is that we depend on a non-official third-party dependency.  perhaps we have some boilerplate code in our service and still match the current behavior? like we did in the experimental unary promise option?

**Comment by chris-kruining** [comment]
> iterator methods seem really cool. the only thing that I see is not acceptable is that we depend on a non-official third-party dependency. perhaps we have some boilerplate code in our service and still match the current behavior? like we did in the experimental unary promise option?

this comment seems to be for #113 I suggest we resume the discussion over there. this PR is purely to enable generation without namespaces

**Comment by thesayyn** [comment]
> > iterator methods seem really cool. the only thing that I see is not acceptable is that we depend on a non-official third-party dependency. perhaps we have some boilerplate code in our service and still match the current behavior? like we did in the experimental unary promise option?
> 
> this comment seems to be for #113 I suggest we resume the discussion over there. this PR is purely to enable generation without namespaces

right sorry.

**Comment by thesayyn** [comment]
yikes.

**Comment by chris-kruining** [comment]
I'll re-add it with just the changes needed for the patch

**Pull request closed without merging**
