### PR TITLE
refactor: migrate to typescript

### PR DESCRIPTION
**Pull request by thesayyn**
closes #94 #110. thanks @koblas @chris-kruining

### CODE REVIEW

**Comment by thesayyn** [comment]
hey fellas. this PR introduces the typescript pipeline. I have figured out most of the things. though I will need your help converting the javascript sources to typescript ones.

- need to get tests working. 
- need to interop with examples to assert that we don't break anything
- need to create an automatic release pipeline in our CI

**Comment by chris-kruining** [comment]
image

Can I get access to I can push to this PR?

**Comment by thesayyn** [comment]
I would like to but only collaborators can get write access.  :(  but I can cherry-pick your changes if you could open a PR that bases this one.  

basically; 

```sh
git checkout typescript
# make your changes 
git commit -m "tb cherry picked"
git push myorigin typescript
```

**Comment by chris-kruining** [comment]
see #114

**Comment by chris-kruining** [comment]
how did the build break?? is the index.js not being compiled?

**Comment by thesayyn** [comment]
> how did the build break?? is the index.js not being compiled?

i got it. everything is working now.

**Comment by chris-kruining** [comment]
I spotted I missed the `tsconfig.json` file but that didn't do much in it's config

**Comment by thesayyn** [comment]
this is almost ready. expect one pesky windows line break issue. I hate windows so much. just pain.

**Comment by koblas** [comment]
You can do it, we're all cheering from the stands!

**Comment by chris-kruining** [comment]
> this is almost ready. except one pesky windows line break issue. I hate windows so much. just pain.

gotta love proprietary bs 🙄

**Comment by thesayyn** [comment]
done. f_u windows.

**Pull request merged**
